default: &default
  adapter: postgresql
  encoding: unicode
  username: nina
  password: secret
  host: localhost

development:
  <<: *default
  database: phonebook_d2_development

test:
  <<: *default
  database: phonebook_d2_test
